{
 "title": "Main",
 "tags": [ "client" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "device",
    "label": "Device",
    "query": "select path from devices where path not like '%/Host'"
   },
   {
    "name": "axis",
    "query": "select substring(path, 'Axes/(.*)/Load$') from dataitems where path like '$device/Axes/%/Load' order by path"
   }
  ]
 },
 "panels": [
  { "title": "Axis Load ($device)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$axis",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "repeat": "axis",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT time, value\nFROM history_float\nWHERE\n  path = concat('$device','/Axes/', '$axis', '/Load')\n  and $__timeFilter(\"time\")\norder by time desc\nlimit 1"
    }
   ]
  },
  { "title": "Timeline", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Timeline ($device)",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT time, value as \"Availability\"\nFROM get_timeline('$device/Availability', $__from, $__to, true, '1d')\n"
    },
    {
     "rawSql": "SELECT time, value as \"Controller Mode\"\nFROM get_timeline('$device/Controller/Path/ControllerMode', $__from, $__to, true, '1d')\n"
    },
    {
     "rawSql": "SELECT time, value as \"Emergency Stop\"\nFROM get_timeline('$device/Controller/EmergencyStop', $__from, $__to, true, '1d')\n"
    },
    {
     "rawSql": "SELECT time, value as \"Execution\"\nFROM get_timeline('$device/Controller/Path/Execution', $__from, $__to, true, '1d')\n"
    },
    {
     "rawSql": "SELECT time, value as \"Equipment Mode / Working\"\nFROM get_timeline('$device/EquipmentModeWorking', $__from, $__to, true, '1h')\n"
    },
    {
     "rawSql": "SELECT time, value as \"Equipment Mode / Delay\"\nFROM get_timeline('$device/EquipmentModeDelay', $__from, $__to, true, '1h')\n"
    },
    {
     "rawSql": "SELECT time, value as \"Equipment Mode / Loaded\"\nFROM get_timeline('$device/EquipmentModeLoaded', $__from, $__to, true, '1h')\n"
    }
   ]
  },
  { "title": "Temperature and Load", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Temperature (C) ($device)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT time, substring(path, 'Axes/(.*)/Temperature') as axis, value as temp\nFROM history_float\nWHERE\n  path like '$device/Axes/%/Temperature' and\n  $__timeFilter(\"time\")\norder by time\n"
    },
    {
     "rawSql": "SELECT time, 'Coolant' as axis, value as \"temp Coolant\"\nFROM history_float\nWHERE\n  path='$device/Systems/Coolant/Temperature' and\n  $__timeFilter(\"time\")\norder by time"
    }
   ]
  },
  {
   "title": "Load ($device)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT time, substring(path, 'Axes/(.*)/Load') as axis, value as load\nFROM history_float\nWHERE\n  path like '$device/Axes/%/Load%' -- note the trailing %, if had to add [name]\n  and $__timeFilter(\"time\")\norder by time"
    }
   ]
  },
  { "title": "Speeds", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Path Feedrate (mm/sec) ($device)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  substring(path, '$device/(.*)') as path,\n  value as feedrate\nFROM history_float\nWHERE\n  path like '$device/Axes/%/AxisFeedrate'\n  and $__timeFilter(\"time\")\nORDER BY time\n"
    }
   ]
  },
  {
   "title": "Spindle Speed ($device)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT time, substring(path, '$device/(.*)') as path, value as speed\nFROM history_float\nWHERE\n  path like '$device/%RotaryVelocity%'\n  and $__timeFilter(\"time\")\norder by time asc"
    }
   ]
  }
 ]
}